# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: localhost
  database: tv_shows
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
#  host: localhost
#  port: 5432

